// Generated by `supabase gen types typescript --linked`, re-exported here so
// Edge Functions and the frontend share one source of truth instead of two
// hand-maintained copies. Regenerate frontend/types/database.types.ts after
// any migration that changes the schema (see README).
export type { Database } from "../../../frontend/types/database.types.ts";
